### ISSUE TITLE
Problem with vcruntime140.dll

### ISSUE THREAD

**Issue by RoccoZero** [ImGuiNET/ImGui.NET-nativebuild#22]
is it possible to build ImGui.NET-nativebuild using /MT?
otherwise cimgui.dll requires vcruntime140.dll and this is a problem for many users

**Comment by zaafar** [comment]
what's wrong with installing Microsoft Visual C++ 2015 - 2022 Redistributable?

**Comment by zaafar** [comment]
Also, I couldn't find the such flags in imgui.net and imgui.net-nativebuild repo.
Is this a https://github.com/cimgui/cimgui issue?

**Comment by RoccoZero** [comment]
I was able to build using the /MT flag
but this is through visual studio

https://stackoverflow.com/questions/14172856/compile-with-mt-instead-of-md-using-cmake
here is some information on how to use cmake "/MT"

**Comment by RoccoZero** [comment]
> what's wrong with installing Microsoft Visual C++ 2015 - 2022 Redistributable?

it's just that my applications are only 1 .exe file and there is no option to install Visual C++ 2015 - 2022

**Comment by zaafar** [comment]
I see, yeah it makes sense to use MT (to reduce the added libs) however I am still failing to understand why is this not a https://github.com/cimgui/cimgui issue (where the actual cmakefile exists) and an imgui.net-nativebuild (or imgui.net) issue.

**Comment by zaafar** [comment]
@sonoro1234 is this something you can help with?

**Comment by sonoro1234** [comment]
It seems that you should be able to set CMAKE_MSVC_RUNTIME_LIBRARY variable in build-native.cmd

**Comment by zaafar** [comment]
sounds good, i will test that.

**Comment by zaafar** [comment]
i did some testing, failed.
not sure what i am doing wrong.
https://github.com/ImGuiNET/ImGui.NET-nativebuild/pull/24

**Comment by sonoro1234** [comment]
generator expresions are to be runned inside CMakeLists.txt
From the command line I would use `-DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded"`

**Comment by RoccoZero** [comment]
> I tried a couple of things, it didn't work. I am feeling like out of my domain.
> 
> @RoccoZero please create a PR for this issue and I will merge it.
> 
> sorry I couldn't do much more than this.

I couldn't do anything, it's hard for me to use cmake
@sonoro1234 pls help

**Comment by sonoro1234** [comment]
Could build with /MTd from build-native.cmd
with `set MSVC_RUNTIME="MultiThreadedDebug"`
and then `cmake -DCMAKE_GENERATOR_PLATFORM=%BUILD_CMAKE_GENERATOR_PLATFORM% -DCMAKE_MSVC_RUNTIME_LIBRARY=%MSVC_RUNTIME% ..\..`

but for this happening cimgui CMakeLists.txt has to be changed with `cmake_policy(SET CMP0091 NEW)` as said in https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html

Just pushed this change to cimgui repo

**Comment by zaafar** [comment]
going to give it 1 more try today, thanks!

**Comment by zaafar** [comment]
it didn't work.

==Changes==
https://github.com/ImGuiNET/ImGui.NET-nativebuild/actions/runs/6254838866

==binaries==
https://github.com/ImGuiNET/ImGui.NET-nativebuild/actions/runs/6254838866

==Result==
![image](https://github.com/ImGuiNET/ImGui.NET-nativebuild/assets/5079646/38d0b2cc-9349-4b59-bd89-99e4afd1de4c)

**Comment by zaafar** [comment]
wait, i forgot pulling latest cimgui.

**Comment by zaafar** [comment]
it worked, going to test imgui.net with it and merge the PR.
@sonoro1234  thanks for the help!

**Comment by RoccoZero** [comment]
> it worked, going to test imgui.net with it and merge the PR. @sonoro1234 thanks for the help!

nice

**Comment by zaafar** [comment]
i have released v1.89.9.2 in imgui.net
its dlls are not dependent on vcruntime140.dll

**Comment by RoccoZero** [comment]
> i have released v1.89.9.2 in imgui.net its dlls are not dependent on vcruntime140.dll

Yes, I already noticed this and started using your version, thank you very much

**Comment by Marlax0** [comment]
Could this be related to an issue I just had?
I woke up this morning and none of my project builds could load ImGui.NET.
New builds, old builds, all of them crashed trying to load ImGui.NET.
`Unable to load DLL 'cimgui' or one of its dependencies: The specified module could not be found.`
The DLL is there where it always has been, I've even tried replacing it with different backups.
I checked for Windows updates, reinstalled Visual C++ 2015 - 2022, restarted my PC, nothing worked.
I ended up rebuilding ImGui.NET-nativebuild and ImGui.NET and it finally fixed the issue.
What? What could have possibly happened?

I'm using an older version (1.89.7), do you think this is a vcruntime140.dll issue?

**Comment by zaafar** [comment]
vcruntime is only added in 1.89.9.2 version of imgui.net
any version before that (e.g. 1.89.9.1 or 1.89.8) doesn't have these changes.

**Comment by Marlax0** [comment]
I guess you haven't heard of this issue before then?
I've been using ImGui.NET for years and this appeared out of nowhere.

**Comment by zaafar** [comment]
you are the first :)
